// In-region semantic search (Phase 3b).
//
// Embeddings are generated by the Supabase `embed` Edge Function (built-in
// gte-small, 384-dim, runs in YOUR Supabase region — no external vendor) and
// stored in the `embeddings` table via pgvector (migration 0076).
//
// Everything here is BEST-EFFORT and gated by the `semanticSearch` setting:
// when the feature is off (the default) or the Edge Function / table aren't
// deployed yet, every function quietly no-ops or returns empty, so callers fall
// back to keyword search and nothing breaks. Accessed via supabase-js + RPCs
// (not Drizzle ORM) so the query vector is cast server-side, robustly, over the
// transaction pooler.

import { createHash } from "crypto";
import { sb } from "@/db/supabase";
import { getAppSettings } from "@/lib/settings";

export type SourceType = "task" | "meeting" | "document";
export type SemanticHit = { sourceType: SourceType; sourceId: number; content: string; similarity: number };

const EMBED_FN = "embed";
const MAX_INPUT = 8000; // gte-small truncates ~512 tokens anyway; keep the payload small

async function semanticEnabled(): Promise<boolean> {
  try {
    return (await getAppSettings()).semanticSearch;
  } catch {
    return false;
  }
}

function hash(s: string): string {
  return createHash("sha256").update(s).digest("hex").slice(0, 32);
}

function toVectorString(v: number[]): string {
  return `[${v.join(",")}]`;
}

/** Embed a single string via the in-region Edge Function. null on any failure. */
async function embedText(text: string): Promise<number[] | null> {
  const input = text.trim().slice(0, MAX_INPUT);
  if (!input) return null;
  try {
    const { data, error } = await sb.functions.invoke(EMBED_FN, { body: { input } });
    if (error) return null;
    const emb = (data as { embedding?: unknown })?.embedding;
    return Array.isArray(emb) && emb.length > 0 ? (emb as number[]) : null;
  } catch {
    return null;
  }
}

/**
 * Index one item's content for semantic search. Best-effort and safe to call
 * fire-and-forget from any write path: it no-ops when the feature is off, when
 * the content is empty, or when the content is unchanged since last index
 * (content_hash), and it never throws.
 */
export async function indexEmbedding(sourceType: SourceType, sourceId: number, content: string, force = false): Promise<void> {
  try {
    if (!sourceId || !content?.trim()) return;
    if (!force && !(await semanticEnabled())) return;
    const trimmed = content.trim().slice(0, MAX_INPUT);
    const h = hash(trimmed);
    // Skip the (paid) embed call if we already have an up-to-date vector.
    const { data: existing } = await sb
      .from("embeddings")
      .select("content_hash")
      .eq("source_type", sourceType)
      .eq("source_id", sourceId)
      .maybeSingle();
    if (existing && (existing as { content_hash?: string }).content_hash === h) return;
    const vec = await embedText(trimmed);
    if (!vec) return;
    await sb.rpc("upsert_embedding", {
      p_source_type: sourceType,
      p_source_id: sourceId,
      p_content: trimmed,
      p_content_hash: h,
      p_embedding: toVectorString(vec),
    });
  } catch {
    /* best-effort: never break the write path */
  }
}

/** Remove an item's embedding (e.g. on delete/archive). Best-effort. */
export async function removeEmbedding(sourceType: SourceType, sourceId: number): Promise<void> {
  try {
    await sb.from("embeddings").delete().eq("source_type", sourceType).eq("source_id", sourceId);
  } catch {
    /* ignore */
  }
}

/**
 * Semantic search across stored embeddings. Returns [] when the feature is off,
 * the query can't be embedded, or nothing is indexed yet — so callers transparently
 * fall back to keyword search.
 */
export async function semanticSearch(
  query: string,
  opts?: { types?: SourceType[]; limit?: number },
): Promise<SemanticHit[]> {
  try {
    if (!query?.trim()) return [];
    if (!(await semanticEnabled())) return [];
    const vec = await embedText(query);
    if (!vec) return [];
    const { data, error } = await sb.rpc("match_embeddings", {
      query_embedding: toVectorString(vec),
      match_count: opts?.limit ?? 12,
      filter_types: opts?.types ?? null,
    });
    if (error || !Array.isArray(data)) return [];
    return (data as Record<string, unknown>[]).map((r) => ({
      sourceType: r.source_type as SourceType,
      sourceId: Number(r.source_id),
      content: r.content as string,
      similarity: Number(r.similarity),
    }));
  } catch {
    return [];
  }
}
