// In-region semantic search (Phase 3b + advanced upgrade S1-S4).
//
// Embeddings are generated by the Supabase `embed` Edge Function (built-in
// gte-small, 384-dim, in YOUR Supabase region — no external vendor) and stored in
// the `embeddings` table (pgvector + a `simple` full-text column). Retrieval is
// HYBRID: Postgres full-text + vector fused by Reciprocal Rank Fusion (the
// hybrid_search RPC). Long content is CHUNKED (one row per passage). Non-English
// text is TRANSLATED to English by Groq before embedding (gte-small is English-only;
// the original text is still stored for full-text, so Swahili/Hindi/Gujarati terms
// match literally too).
//
// Everything is BEST-EFFORT and gated by the `semanticSearch` setting: off (default)
// or any failure => no-op / empty, so callers fall back to keyword search.

import { createHash } from "crypto";
import { sb } from "@/db/supabase";
import { getAppSettings, getGroqKey } from "@/lib/settings";
import { callGroqText } from "@/lib/ai-json";
import { GROQ_FAST } from "@/lib/ai-models";

export type SourceType = "task" | "meeting" | "document" | "person";
export type SemanticHit = { sourceType: SourceType; sourceId: number; content: string; similarity: number };

const EMBED_FN = "embed";
const CHUNK_CHARS = 1800;   // ~450 tokens — within gte-small's 512-token cap
const CHUNK_OVERLAP = 250;  // ~14% overlap so a fact split across a boundary survives
const MAX_CHUNKS = 24;      // bound a pathologically long document
const MAX_TOTAL = 40000;    // hard cap on input characters

async function semanticEnabled(): Promise<boolean> {
  try {
    return (await getAppSettings()).semanticSearch;
  } catch {
    return false;
  }
}

function hash(s: string): string {
  return createHash("sha256").update(s).digest("hex").slice(0, 32);
}

function toVectorString(v: number[]): string {
  return `[${v.join(",")}]`;
}

/** Split text into ~CHUNK_CHARS passages with overlap, breaking on sentence/line
 *  boundaries where possible. Short text returns a single chunk. */
function chunkText(text: string): string[] {
  const t = text.replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").trim();
  if (!t) return [];
  if (t.length <= CHUNK_CHARS) return [t];
  const chunks: string[] = [];
  let i = 0;
  while (i < t.length && chunks.length < MAX_CHUNKS) {
    let end = Math.min(i + CHUNK_CHARS, t.length);
    if (end < t.length) {
      const slice = t.slice(i, end);
      const brk = Math.max(slice.lastIndexOf(". "), slice.lastIndexOf("? "), slice.lastIndexOf("! "), slice.lastIndexOf("\n"));
      const sp = slice.lastIndexOf(" ");
      const cut = brk > CHUNK_CHARS * 0.5 ? brk + 1 : sp > CHUNK_CHARS * 0.5 ? sp : slice.length;
      end = i + cut;
    }
    const piece = t.slice(i, end).trim();
    if (piece) chunks.push(piece);
    if (end >= t.length) break;
    i = Math.max(end - CHUNK_OVERLAP, i + 1);
  }
  return chunks;
}

/** Heuristic: would the English-only embed model fail on this text? Devanagari/
 *  Gujarati scripts always; Swahili by a few high-frequency function words. */
function looksNonEnglish(text: string): boolean {
  if (/[ऀ-ॿ઀-૿]/.test(text)) return true; // Hindi / Gujarati
  const sw = text.match(/\b(tafadhali|asante|malipo|risiti|ankara|tarehe|kuhusu|kwenye|ambaye|kwa|ya|wa|na|ni|za|fedha|mkataba|barua)\b/gi);
  return !!sw && sw.length >= 3;
}

/** Translate non-English text to English via Groq so gte-small can embed it.
 *  Best-effort: returns the original on AI-off or any failure. */
async function maybeTranslate(text: string): Promise<string> {
  const t = text.trim();
  if (!t || !looksNonEnglish(t)) return text;
  try {
    const apiKey = await getGroqKey();
    if (!apiKey) return text;
    const res = await callGroqText({
      apiKey,
      model: GROQ_FAST,
      maxTokens: 1024,
      temperature: 0,
      messages: [
        { role: "system", content: "Translate the user's text to English. Reply with ONLY the English translation — no preamble, no quotes. Preserve names, numbers, dates, codes and amounts exactly." },
        { role: "user", content: t.slice(0, 6000) },
      ],
    });
    return res.ok && res.text ? res.text.trim() : text;
  } catch {
    return text;
  }
}

/** Embed a single string via the in-region Edge Function. null on any failure. */
async function embedText(text: string): Promise<number[] | null> {
  const input = text.trim().slice(0, CHUNK_CHARS * 2);
  if (!input) return null;
  try {
    const { data, error } = await sb.functions.invoke(EMBED_FN, { body: { input } });
    if (error) return null;
    const emb = (data as { embedding?: unknown })?.embedding;
    return Array.isArray(emb) && emb.length > 0 ? (emb as number[]) : null;
  } catch {
    return null;
  }
}

/**
 * Index one item's content for hybrid search. Chunks it, embeds each chunk (the
 * English translation when needed), and replaces the parent's rows atomically.
 * Best-effort + safe to call fire-and-forget: no-ops when the feature is off,
 * content is empty, or unchanged since last index (content_hash), and never throws.
 * `force` bypasses the on/off gate (for the backfill script).
 */
export async function indexEmbedding(sourceType: SourceType, sourceId: number, content: string, force = false): Promise<void> {
  try {
    if (!sourceId || !content?.trim()) return;
    if (!force && !(await semanticEnabled())) return;
    const full = content.trim().slice(0, MAX_TOTAL);
    const h = hash(full);
    const { data: existing } = await sb
      .from("embeddings")
      .select("content_hash")
      .eq("source_type", sourceType)
      .eq("source_id", sourceId)
      .limit(1)
      .maybeSingle();
    if (existing && (existing as { content_hash?: string }).content_hash === h) return;

    const chunks = chunkText(full);
    if (!chunks.length) return;
    const out: { i: number; content: string; e: string }[] = [];
    for (let i = 0; i < chunks.length; i++) {
      const vec = await embedText(await maybeTranslate(chunks[i]));
      if (vec) out.push({ i, content: chunks[i], e: toVectorString(vec) });
    }
    if (!out.length) return;
    await sb.rpc("replace_embeddings", {
      p_source_type: sourceType,
      p_source_id: sourceId,
      p_content_hash: h,
      p_chunks: out,
    });
  } catch {
    /* best-effort: never break the write path */
  }
}

/** Remove all of an item's chunks (e.g. on delete/archive). Best-effort. */
export async function removeEmbedding(sourceType: SourceType, sourceId: number): Promise<void> {
  try {
    await sb.from("embeddings").delete().eq("source_type", sourceType).eq("source_id", sourceId);
  } catch {
    /* ignore */
  }
}

/**
 * Hybrid search: full-text + vector fused by RRF, rolled up to the best chunk per
 * parent. Returns [] when the feature is off, the query can't be embedded, or
 * nothing is indexed — so callers fall back to keyword search. `similarity` carries
 * the RRF score (higher = better; not a cosine value).
 */
export async function hybridSearch(
  query: string,
  opts?: { types?: SourceType[]; limit?: number },
): Promise<SemanticHit[]> {
  try {
    if (!query?.trim()) return [];
    if (!(await semanticEnabled())) return [];
    const vec = await embedText(await maybeTranslate(query));
    if (!vec) return [];
    const { data, error } = await sb.rpc("hybrid_search", {
      query_text: query.trim().slice(0, 1000),
      query_embedding: toVectorString(vec),
      match_count: opts?.limit ?? 12,
      filter_types: opts?.types ?? null,
    });
    if (error || !Array.isArray(data)) return [];
    return (data as Record<string, unknown>[]).map((r) => ({
      sourceType: r.source_type as SourceType,
      sourceId: Number(r.source_id),
      content: r.content as string,
      similarity: Number(r.score),
    }));
  } catch {
    return [];
  }
}

/** Back-compat alias — now hybrid (full-text + vector). */
export async function semanticSearch(
  query: string,
  opts?: { types?: SourceType[]; limit?: number },
): Promise<SemanticHit[]> {
  return hybridSearch(query, opts);
}
