// In-region semantic search (Phase 3b + advanced upgrade S1-S4).
//
// Embeddings are generated by the Supabase `embed` Edge Function (built-in
// gte-small, 384-dim, in YOUR Supabase region — no external vendor) and stored in
// the `embeddings` table (pgvector + a `simple` full-text column). Retrieval is
// HYBRID: Postgres full-text + vector fused by Reciprocal Rank Fusion (the
// hybrid_search RPC). Long content is CHUNKED (one row per passage). Non-English
// text is TRANSLATED to English by Groq before embedding (gte-small is English-only;
// the original text is still stored for full-text, so Swahili/Hindi/Gujarati terms
// match literally too).
//
// Everything is BEST-EFFORT and gated by the `semanticSearch` setting: off (default)
// or any failure => no-op / empty, so callers fall back to keyword search.

import { createHash } from "crypto";
import { sb } from "@/db/supabase";
import { getAppSettings, getAiKey } from "@/lib/settings";
import { callAIText } from "@/lib/ai-json";
import { AI_FAST } from "@/lib/ai-models";

export type SourceType =
  | "task"
  | "document"
  | "person"
  | "company"
  | "vendor"
  | "asset"
  | "governance"
  | "risk"
  | "pipeline"
  | "commitment"
  /** Notes (Phase 1). Not indexed yet — the EntityDef arrives in Phase 6; this
   *  member exists so the module can have an ENTITY_VIEWS entry like every other
   *  record type. */
  | "note"
  /** The recruitment desk (Phase 1) — Oracle Consultancy's agency. Not indexed
   *  yet; the EntityDefs arrive in Phase 8. These members exist so the module can
   *  have ENTITY_VIEWS entries like every other record type. */
  | "rec_client"
  | "rec_candidate"
  | "rec_job_order"
  /** CocoZuri Operations (Phase 1) — Furaha Innovation's chocolate business,
   *  rebuilt from 18 spreadsheets. Not indexed yet; the EntityDefs arrive with
   *  the invoices. These members exist so the module can have ENTITY_VIEWS
   *  entries like every other record type. */
  | "cz_product"
  | "cz_customer"
  /** The PES trading module (Stages 2–5). Four record types, each carrying a
   *  reference number somebody quotes down the phone — a PO, a bill of lading,
   *  an RFQ, an invoice — which is exactly what a search box is for. */
  | "ops_order"
  | "ops_shipment"
  | "ops_enquiry"
  | "ops_invoice"
  /** Stage 7 — money out, and bids being chased. */
  | "ops_payment"
  | "ops_tender"
  /** Capital projects — the construction jobs rebuilt from the PES workbook
   *  (Phase 1). Same arrangement as `note` above: NOT indexed yet, so there is
   *  deliberately no EntityDef in entity-registry.ts. The member exists so the
   *  module can have an ENTITY_VIEWS entry and inherit the standard list and
   *  record screens. Making it searchable later is one EntityDef and nothing
   *  else — see the FORWARD RULE in CLAUDE.md. */
  | "project";

// Lifecycle of an indexed source row. `active` = current/live; `history` = the
// row still EXISTS but is archived/closed/inactive (kept searchable, just
// labelled so callers can include or exclude past records). Old vectors written
// before migration 0094 default to `active` in the DB.
export type Lifecycle = "active" | "history";

export type SemanticHit = {
  sourceType: SourceType;
  sourceId: number;
  content: string;
  similarity: number;
  lifecycle: Lifecycle;
};

const EMBED_FN = "embed";
const CHUNK_CHARS = 1800;   // ~450 tokens — within gte-small's 512-token cap
const CHUNK_OVERLAP = 250;  // ~14% overlap so a fact split across a boundary survives
const MAX_CHUNKS = 24;      // bound a pathologically long document
const MAX_TOTAL = 40000;    // hard cap on input characters

async function semanticEnabled(): Promise<boolean> {
  try {
    return (await getAppSettings()).semanticSearch;
  } catch {
    return false;
  }
}

function hash(s: string): string {
  return createHash("sha256").update(s).digest("hex").slice(0, 32);
}

function toVectorString(v: number[]): string {
  return `[${v.join(",")}]`;
}

/** Split text into ~CHUNK_CHARS passages with overlap, breaking on sentence/line
 *  boundaries where possible. Short text returns a single chunk. */
function chunkText(text: string): string[] {
  const t = text.replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").trim();
  if (!t) return [];
  if (t.length <= CHUNK_CHARS) return [t];
  const chunks: string[] = [];
  let i = 0;
  while (i < t.length && chunks.length < MAX_CHUNKS) {
    let end = Math.min(i + CHUNK_CHARS, t.length);
    if (end < t.length) {
      const slice = t.slice(i, end);
      const brk = Math.max(slice.lastIndexOf(". "), slice.lastIndexOf("? "), slice.lastIndexOf("! "), slice.lastIndexOf("\n"));
      const sp = slice.lastIndexOf(" ");
      const cut = brk > CHUNK_CHARS * 0.5 ? brk + 1 : sp > CHUNK_CHARS * 0.5 ? sp : slice.length;
      end = i + cut;
    }
    const piece = t.slice(i, end).trim();
    if (piece) chunks.push(piece);
    if (end >= t.length) break;
    i = Math.max(end - CHUNK_OVERLAP, i + 1);
  }
  return chunks;
}

/** Heuristic: would the English-only embed model fail on this text? Devanagari/
 *  Gujarati scripts always; Swahili by a few high-frequency function words. */
function looksNonEnglish(text: string): boolean {
  if (/[ऀ-ॿ઀-૿]/.test(text)) return true; // Hindi / Gujarati
  const sw = text.match(/\b(tafadhali|asante|malipo|risiti|ankara|tarehe|kuhusu|kwenye|ambaye|kwa|ya|wa|na|ni|za|fedha|mkataba|barua)\b/gi);
  return !!sw && sw.length >= 3;
}

/** Translate non-English text to English via Groq so gte-small can embed it.
 *  Best-effort: returns the original on AI-off or any failure. */
async function maybeTranslate(text: string): Promise<string> {
  const t = text.trim();
  if (!t || !looksNonEnglish(t)) return text;
  try {
    const apiKey = await getAiKey();
    if (!apiKey) return text;
    const res = await callAIText({
      apiKey,
      model: AI_FAST,
      maxTokens: 1024,
      temperature: 0,
      messages: [
        { role: "system", content: "Translate the user's text to English. Reply with ONLY the English translation — no preamble, no quotes. Preserve names, numbers, dates, codes and amounts exactly." },
        { role: "user", content: t.slice(0, 6000) },
      ],
    });
    return res.ok && res.text ? res.text.trim() : text;
  } catch {
    return text;
  }
}

/** Embed a single string via the in-region Edge Function. null on any failure. */
async function embedText(text: string): Promise<number[] | null> {
  const input = text.trim().slice(0, CHUNK_CHARS * 2);
  if (!input) return null;
  try {
    const { data, error } = await sb.functions.invoke(EMBED_FN, { body: { input } });
    if (error) return null;
    const emb = (data as { embedding?: unknown })?.embedding;
    return Array.isArray(emb) && emb.length > 0 ? (emb as number[]) : null;
  } catch {
    return null;
  }
}

/* B2 — QUERY-EMBEDDING CACHE. Every semantic search embeds the QUERY first, an
 * Edge-Function round-trip (latency + egress). Repeated/near-repeated searches
 * ("terra green", "brief me", a re-typed ⌘K query, a rewritten follow-up that
 * lands on the same text) recompute the SAME vector. This is a tiny in-memory,
 * short-TTL, bounded cache around ONLY the query-embed call, keyed on the
 * normalised query text. Document/content embeddings are NOT cached (they're
 * write-once per chunk and already hash-gated). Fail-open: any cache trouble
 * falls straight through to a normal embed.
 *
 * In-memory per server instance — a warm Vercel function reuses it across
 * requests; a cold start simply starts empty. No cross-request correctness risk:
 * gte-small is deterministic, so a cached vector equals a fresh one. */
const QUERY_EMBED_TTL_MS = 5 * 60 * 1000; // 5 min — long enough for a search session, short enough to stay fresh
const QUERY_EMBED_MAX = 200;              // bound the map so it can't grow unboundedly
const queryEmbedCache = new Map<string, { vec: number[]; at: number }>();

/** Normalise a query to its cache key: lower-cased, whitespace-collapsed, capped.
 *  Separator-insensitivity isn't needed — the Edge Function embeds the raw text,
 *  so only byte-identical (post-normalise) queries may safely share a vector. */
function queryCacheKey(text: string): string {
  return text.trim().toLowerCase().replace(/\s+/g, " ").slice(0, 400);
}

/** Embed a QUERY string, reusing a recent identical embed when possible. Wraps
 *  embedText; only used by the search path. Fail-open on every branch. */
async function embedQuery(text: string): Promise<number[] | null> {
  const key = queryCacheKey(text);
  if (!key) return embedText(text);
  const now = Date.now();
  try {
    const hit = queryEmbedCache.get(key);
    if (hit && now - hit.at < QUERY_EMBED_TTL_MS) return hit.vec;
  } catch {
    /* cache read trouble → embed normally */
  }
  const vec = await embedText(text);
  if (vec) {
    try {
      // Evict the oldest entry when full (Map preserves insertion order, so the
      // first key is the oldest). Keeps the cache bounded without a heavy LRU.
      if (queryEmbedCache.size >= QUERY_EMBED_MAX) {
        const oldest = queryEmbedCache.keys().next().value;
        if (oldest !== undefined) queryEmbedCache.delete(oldest);
      }
      queryEmbedCache.set(key, { vec, at: now });
    } catch {
      /* cache write trouble → just skip caching */
    }
  }
  return vec;
}

/**
 * Index one item's content for hybrid search. Chunks it, embeds each chunk (the
 * English translation when needed), and replaces the parent's rows atomically.
 * Best-effort + safe to call fire-and-forget: no-ops when the feature is off,
 * content is empty, or unchanged since last index (content_hash + lifecycle),
 * and never throws. `force` bypasses the on/off gate (for the backfill script).
 * `lifecycle` labels the row as current ("active") or archived/closed/inactive
 * ("history") — history is kept searchable, never deleted; defaults to "active"
 * so existing callers keep their behaviour.
 */
export async function indexEmbedding(
  sourceType: SourceType,
  sourceId: number,
  content: string,
  force = false,
  lifecycle: Lifecycle = "active",
): Promise<void> {
  try {
    if (!sourceId || !content?.trim()) return;
    if (!force && !(await semanticEnabled())) return;
    const full = content.trim().slice(0, MAX_TOTAL);
    const h = hash(full);
    const { data: existing } = await sb
      .from("embeddings")
      .select("content_hash,lifecycle")
      .eq("source_type", sourceType)
      .eq("source_id", sourceId)
      .limit(1)
      .maybeSingle();
    // Skip only when BOTH the content and the lifecycle are unchanged, so a row
    // flipping active⇄history is always re-stamped even if its text is identical.
    const prev = existing as { content_hash?: string; lifecycle?: string } | null;
    if (prev && prev.content_hash === h && (prev.lifecycle ?? "active") === lifecycle) return;

    const chunks = chunkText(full);
    if (!chunks.length) return;
    const out: { i: number; content: string; e: string }[] = [];
    for (let i = 0; i < chunks.length; i++) {
      const vec = await embedText(await maybeTranslate(chunks[i]));
      if (vec) out.push({ i, content: chunks[i], e: toVectorString(vec) });
    }
    if (!out.length) return;
    await sb.rpc("replace_embeddings", {
      p_source_type: sourceType,
      p_source_id: sourceId,
      p_content_hash: h,
      p_chunks: out,
      p_lifecycle: lifecycle,
    });
  } catch {
    /* best-effort: never break the write path */
  }
}

/** Remove all of an item's chunks (e.g. on delete/archive). Best-effort. */
export async function removeEmbedding(sourceType: SourceType, sourceId: number): Promise<void> {
  try {
    await sb.from("embeddings").delete().eq("source_type", sourceType).eq("source_id", sourceId);
  } catch {
    /* ignore */
  }
}

export type SearchOpts = {
  types?: SourceType[];
  limit?: number;
  /**
   * Which lifecycle of records to search:
   *   "active"  (default) — current/live records only, as callers expected before
   *   "history"           — archived/closed/inactive records only
   *   "all"               — both current and historical
   * Maps to the RPC's `filter_lifecycle` arg (NULL = all).
   */
  lifecycle?: Lifecycle | "all";
};

/**
 * Hybrid search: full-text + vector fused by RRF, rolled up to the best chunk per
 * parent. Returns [] when the feature is off, the query can't be embedded, or
 * nothing is indexed — so callers fall back to keyword search. `similarity` carries
 * the RRF score (higher = better; not a cosine value). Defaults to current records
 * only (`lifecycle: "active"`), so existing callers never surface archived history.
 *
 * Best-effort: if the deployed DB still has the OLD hybrid_search signature (no
 * lifecycle arg — i.e. before migration 0094 is applied), the RPC errors and we
 * return [] so prod simply falls back to keyword search until the migration lands.
 */
export async function hybridSearch(
  query: string,
  opts?: SearchOpts,
): Promise<SemanticHit[]> {
  try {
    if (!query?.trim()) return [];
    if (!(await semanticEnabled())) return [];
    // B2 — reuse a recent identical query embed (short-TTL, bounded cache).
    const vec = await embedQuery(await maybeTranslate(query));
    if (!vec) return [];
    const lifecycle = opts?.lifecycle ?? "active";
    const { data, error } = await sb.rpc("hybrid_search", {
      query_text: query.trim().slice(0, 1000),
      query_embedding: toVectorString(vec),
      match_count: opts?.limit ?? 12,
      filter_types: opts?.types ?? null,
      // NULL = all lifecycles; otherwise restrict to the one asked for.
      filter_lifecycle: lifecycle === "all" ? null : lifecycle,
    });
    if (error || !Array.isArray(data)) return [];
    return (data as Record<string, unknown>[]).map((r) => ({
      sourceType: r.source_type as SourceType,
      sourceId: Number(r.source_id),
      content: r.content as string,
      similarity: Number(r.score),
      lifecycle: ((r.lifecycle as string) === "history" ? "history" : "active") as Lifecycle,
    }));
  } catch {
    return [];
  }
}

/** Back-compat alias — now hybrid (full-text + vector). */
export async function semanticSearch(
  query: string,
  opts?: SearchOpts,
): Promise<SemanticHit[]> {
  return hybridSearch(query, opts);
}
