CREATE INDEX IF NOT EXISTS "announcement_comments_announcement_idx" ON "announcement_comments" USING btree ("announcement_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "announcement_receipts_recipient_idx" ON "announcement_receipts" USING btree ("recipient");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "asset_assignments_asset_idx" ON "asset_assignments" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "asset_assignments_person_idx" ON "asset_assignments" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "assets_company_idx" ON "assets" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "assets_assigned_person_idx" ON "assets" USING btree ("assigned_to_person_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "attendance_date_idx" ON "attendance" USING btree ("date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calendar_events_start_idx" ON "calendar_events" USING btree ("start_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calendar_events_company_idx" ON "calendar_events" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_messages_thread_idx" ON "chat_messages" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_participants_participant_idx" ON "chat_participants" USING btree ("participant");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "company_requirements_document_idx" ON "company_requirements" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_company_idx" ON "documents" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_person_idx" ON "documents" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_vendor_idx" ON "documents" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_file_hash_idx" ON "documents" USING btree ("file_hash");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leave_requests_person_idx" ON "leave_requests" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leave_requests_status_idx" ON "leave_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notifications_recipient_idx" ON "notifications" USING btree ("recipient");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "outbox_person_idx" ON "outbox" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person_companies_company_idx" ON "person_companies" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person_requirements_document_idx" ON "person_requirements" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "public_holidays_date_idx" ON "public_holidays" USING btree ("date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reporting_lines_manager_idx" ON "reporting_lines" USING btree ("manager_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stock_issues_item_idx" ON "stock_issues" USING btree ("item_code");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stock_purchases_item_idx" ON "stock_purchases" USING btree ("item_code");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_assignees_person_idx" ON "task_assignees" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_updates_task_idx" ON "task_updates" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tasks_company_idx" ON "tasks" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tasks_owner_idx" ON "tasks" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tasks_status_idx" ON "tasks" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tasks_created_by_idx" ON "tasks" USING btree ("created_by_person_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "todos_person_idx" ON "todos" USING btree ("person_id");