import type { Metadata, Viewport } from "next";
import { Suspense } from "react";
import { MotionConfig } from "framer-motion";
import { Inter } from "next/font/google";
import "./globals.css";

// One self-hosted webfont so the app renders identically on every device
// (Windows/iPhone/Mac), instead of the per-device system font. Exposed as the
// CSS variable --font-inter, which globals.css feeds into --font-sans.
const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
import { ThemeProvider } from "@/components/theme-provider";
import { TopPillServer } from "@/components/top-pill-server";
import { CommandPaletteProvider } from "@/components/command-palette";
import { RecentsTracker } from "@/components/recents-tracker";
import { ToastProvider } from "@/components/toast";
import { UndoBanner } from "@/components/undo-banner";
import { DensityScript } from "@/components/density-toggle";
import { FocusScript } from "@/components/focus-mode";
import { PortalPrefsScript } from "@/components/portal-prefs";
import { InstallPromptScript } from "@/components/install-app";
import { ShellThemeScript } from "@/components/shell-theme";
import { PageTransition } from "@/components/page-transition";
import { ContextActionsProvider } from "@/components/context-actions";
import { GlobalDrawers } from "@/components/global-drawers";
import { ServiceWorkerRegister } from "@/components/service-worker-register";
import { IosResume } from "@/components/ios-resume";
import { HideOnPortal } from "@/components/hide-on-portal";
import { DeskSidebar, DESK_RAIL_COOKIE } from "@/components/desk-sidebar";
import { cookies } from "next/headers";
import { NavVisibilityProvider } from "@/components/nav-visibility";
import { AppSplash } from "@/components/app-splash";
import { ActivityPinger } from "@/components/activity-pinger";
import { getAppSettings } from "@/lib/settings";
import { appBaseUrl } from "@/lib/app-url";

export const metadata: Metadata = {
  // Absolute base so link-preview crawlers (WhatsApp/Twilio) resolve OG image URLs.
  metadataBase: new URL(appBaseUrl()),
  title: "Oracle Consultancy Limited — Operations",
  description: "Chief-of-Staff administrator for Oracle Consultancy",
  manifest: "/manifest.json",
  appleWebApp: { capable: true, statusBarStyle: "default", title: "Oracle Consultancy" },
  icons: {
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  // Branded card shown when a portal link is shared in WhatsApp/chat.
  openGraph: {
    type: "website",
    siteName: "Oracle Consultancy",
    title: "Portal — your tasks, leave & updates",
    description: "Your tasks, leave and updates — sign in to the portal.",
    // Landscape banner so WhatsApp/social render a LARGE card (a square image
    // collapses to a tiny thumbnail). 1200x630 generated by /api/og-banner.
    images: [{ url: "/api/og-banner", width: 1200, height: 630, alt: "Oracle Consultancy staff portal" }],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Lock zoom so focusing a small input doesn't trigger iOS Safari's auto-zoom
  // (and the resulting layout misalignment). The app behaves like a native shell.
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

export default async function RootLayout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
  const { operatorName, voiceLanguage, commandCentrePaused } = await getAppSettings();
  // The rail's width, from its cookie, so <main>'s gutter is correct in the FIRST
  // paint. Without this the gutter arrived an effect late and content began life
  // underneath the rail — see the note in `portal-sidebar.tsx`.
  const railCollapsed = (await cookies()).get(DESK_RAIL_COOKIE)?.value === "1";
  return (
    <html lang="en-GB" className={inter.variable} suppressHydrationWarning>
      <head>
        <DensityScript />
        <FocusScript />
        <PortalPrefsScript />
        <InstallPromptScript />
        <ShellThemeScript />
      </head>
      {/* ⚠️ ALWAYS RESERVE THE SCROLLBAR'S SPACE, OR EVERY PAGE CHANGE JUMPS
          15px SIDEWAYS.
          `PageTransition` crossfades routes, so for ~260ms BOTH pages are
          mounted. The scroll height changes across that window, the body's
          scrollbar appears or disappears with it, and the whole content shifts
          by the scrollbar's width and back. Traced frame by frame in the staff
          portal: `main` went 1009 → 1024 → 1009 on a single click. The sidebar
          is `fixed`, so it alone stayed still — which is exactly why it read as
          "the sidebar is moving". It was everything else.
          ⚠️ **`body`, NOT `html`** — measured: with the gutter on `html` the jump
          survives (998 → 1014), because the body is the scroll container here.
          ⚠️ **INLINE, not `globals.css`** — Tailwind v4's Lightning CSS strips
          `scrollbar-gutter` out of the stylesheet entirely; the `.note-scroller`
          rule was lost the same way and is set inline for the same reason. */}
      <body style={{ scrollbarGutter: "stable" }}>
        <AppSplash />
        <ActivityPinger />
        <ThemeProvider>
          <MotionConfig reducedMotion="user">
          <ToastProvider>
            <UndoBanner />
            <Suspense>
            <CommandPaletteProvider operatorName={operatorName} voiceLanguage={voiceLanguage}>
              <NavVisibilityProvider value={{ commandCentrePaused }}>
              <RecentsTracker />
              <ContextActionsProvider>
                {/* Bottom padding clears the floating bottom pill on mobile/tablet.
                    From xl up the pill moves to the vertical SidePill on the left, so
                    there's nothing at the bottom to clear — reclaim that space. */}
                {/* Top padding respects the notch/status-bar safe area so the
                    hero isn't clipped in the installed PWA (env inset is 0 in a
                    normal browser, so desktop is unaffected). */}
                {/* The working area uses the WIDTH OF THE SCREEN (Desk / Stage 2):
                    a list is a workspace, and a 1100px column left ~400px of dead
                    grey down each side of a wide monitor. 1600px is the stop, so
                    a 27" display doesn't stretch rows to absurdity. Records cap
                    themselves narrower for readability — see RecordPage. */}
                <HideOnPortal>
                  <Suspense>
                    <DeskSidebar initialCollapsed={railCollapsed} />
                  </Suspense>
                </HideOnPortal>
                <main
                  style={{ "--desk-sidebar": railCollapsed ? "56px" : "208px" } as React.CSSProperties}
                  className="pt-[max(1.5rem,env(safe-area-inset-top))] px-4 sm:px-6 lg:px-8 pb-28 md:pb-32 xl:pb-12"
                >
                  <div className="mx-auto max-w-[1600px]">
                    {/* ⚠️ `stableUnder`: inside /portal this wrapper must never re-key —
                        it contains the portal's FIXED sidebar, and re-animating it
                        breaks `fixed` and remounts the rail on every click. The
                        portal layout runs its own PageTransition around just the
                        page. See the note in page-transition.tsx. */}
                    <PageTransition stableUnder={["/portal"]}>{children}</PageTransition>
                  </div>
                </main>
                {modal}
                <HideOnPortal>
                  <Suspense>
                    <TopPillServer />
                  </Suspense>
                </HideOnPortal>
              </ContextActionsProvider>
              <HideOnPortal>
                <GlobalDrawers />
              </HideOnPortal>
              <ServiceWorkerRegister />
              <IosResume />
              </NavVisibilityProvider>
            </CommandPaletteProvider>
            </Suspense>
          </ToastProvider>
          </MotionConfig>
        </ThemeProvider>
      </body>
    </html>
  );
}
