import { getAllTasks, computeCompanyKpis } from "@/lib/queries";
import { isOpen } from "@/lib/derive";
import { PageHeader, Card } from "@/components/ui";
import { CopyButton } from "@/components/copy-button";
import { DigestNarrative } from "@/components/digest-narrative";
import { FileText } from "lucide-react";

export const dynamic = "force-dynamic";

function fmtDate(d: Date | null) {
  if (!d) return "—";
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

function isThisWeek(d: Date | null) {
  if (!d) return false;
  const now = new Date();
  const end = new Date(now);
  end.setDate(end.getDate() + 7);
  return d >= now && d <= end;
}

function wasRecentlyClosed(d: Date | null) {
  if (!d) return false;
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - 7);
  return d >= cutoff;
}

export default async function DigestPage() {
  const rows = await getAllTasks();
  const kpis = computeCompanyKpis(rows);
  const today = new Date().toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });

  const overdue = rows.filter(r => (r.flag === "overdue" || r.flag === "escalate-now") && isOpen(r.status));
  const escalated = rows.filter(r => (r.status === "Escalated" || r.escalation === "Yes") && isOpen(r.status));
  const critical = rows.filter(r => r.priority === "Critical" && isOpen(r.status) && r.flag !== "overdue" && r.flag !== "escalate-now");
  const dueSoon = rows.filter(r => isThisWeek(r.deadline) && isOpen(r.status) && r.flag !== "overdue");
  const recentlyClosed = rows.filter(r => (r.status === "Completed" || r.status === "Closed") && wasRecentlyClosed(r.closedDate));

  // Build the plain-text digest
  const lines: string[] = [
    `📊 COS WEEKLY DIGEST — ${today.toUpperCase()}`,
    `Oracle Group · Chief of Staff Command Center`,
    ``,
  ];

  if (overdue.length > 0) {
    lines.push(`🔴 OVERDUE (${overdue.length})`);
    for (const r of overdue) {
      const dtd = typeof r.daysToDeadline === "number" ? `${Math.abs(r.daysToDeadline)}d late` : "";
      lines.push(`• [${r.code}] ${r.companyName}: ${r.actionItem}${dtd ? ` — ${dtd}` : ""}${r.assignees.length ? ` (${r.assignees.join(", ")})` : ""}`);
    }
    lines.push(``);
  }

  if (escalated.length > 0) {
    lines.push(`🚨 ESCALATED (${escalated.length})`);
    for (const r of escalated) {
      lines.push(`• [${r.code}] ${r.companyName}: ${r.actionItem}${r.latestUpdate ? `\n  → ${r.latestUpdate}` : ""}`);
    }
    lines.push(``);
  }

  if (critical.length > 0) {
    lines.push(`⚠️ CRITICAL PRIORITY (${critical.length})`);
    for (const r of critical) {
      lines.push(`• [${r.code}] ${r.companyName}: ${r.actionItem}${r.deadline ? ` — due ${fmtDate(r.deadline)}` : ""}`);
    }
    lines.push(``);
  }

  if (dueSoon.length > 0) {
    lines.push(`📅 DUE THIS WEEK (${dueSoon.length})`);
    for (const r of dueSoon) {
      lines.push(`• [${r.code}] ${r.companyName}: ${r.actionItem} — due ${fmtDate(r.deadline)}`);
    }
    lines.push(``);
  }

  lines.push(`📋 COMPANY SNAPSHOT`);
  for (const c of kpis) {
    const parts = [];
    if (c.open) parts.push(`${c.open} open`);
    if (c.overdue) parts.push(`${c.overdue} overdue`);
    if (c.critical) parts.push(`${c.critical} critical`);
    if (c.escalated) parts.push(`${c.escalated} escalated`);
    if (c.completed) parts.push(`${c.completed} completed`);
    lines.push(`${c.name}: ${parts.join(" · ") || "all clear ✓"}`);
  }
  lines.push(``);

  if (recentlyClosed.length > 0) {
    lines.push(`✅ RECENTLY COMPLETED (${recentlyClosed.length})`);
    for (const r of recentlyClosed.slice(0, 10)) {
      lines.push(`• [${r.code}] ${r.companyName}: ${r.actionItem}`);
    }
    lines.push(``);
  }

  lines.push(`─────────────────────────`);
  lines.push(`Total open: ${rows.filter(r => isOpen(r.status)).length} · Overdue: ${overdue.length} · Generated by COS`);

  const digestText = lines.join("\n");

  // Build compact stats payload for AI narrative
  const narrativeStats = {
    totalOpen: rows.filter(r => isOpen(r.status)).length,
    overdue: overdue.slice(0, 10).map(r => ({
      code: r.code, company: r.companyName, action: r.actionItem,
      daysLate: typeof r.daysToDeadline === "number" ? Math.abs(r.daysToDeadline) : undefined,
      assignees: r.assignees,
    })),
    escalated: escalated.slice(0, 10).map(r => ({
      code: r.code, company: r.companyName, action: r.actionItem,
      latestUpdate: r.latestUpdate || undefined,
    })),
    critical: critical.slice(0, 10).map(r => ({
      code: r.code, company: r.companyName, action: r.actionItem,
      deadline: r.deadline ? fmtDate(r.deadline) : undefined,
    })),
    dueSoon: dueSoon.slice(0, 10).map(r => ({
      code: r.code, company: r.companyName, action: r.actionItem,
      deadline: r.deadline ? fmtDate(r.deadline) : undefined,
    })),
    recentlyClosed: recentlyClosed.slice(0, 5).map(r => ({
      code: r.code, company: r.companyName, action: r.actionItem,
    })),
    companies: kpis.map(c => ({
      name: c.name, open: c.open, overdue: c.overdue, critical: c.critical,
      escalated: c.escalated, completed: c.completed,
    })),
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex items-center justify-between gap-4">
        <PageHeader
          title="Weekly Digest"
          sub={`Auto-generated summary · ${today}`}
        />
        <CopyButton text={digestText} label="Copy to Clipboard" />
      </div>

      <DigestNarrative stats={narrativeStats} />

      {/* Alert summary */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { label: "Overdue", count: overdue.length, color: "text-danger bg-danger/5 border-danger/20" },
          { label: "Escalated", count: escalated.length, color: "text-danger bg-danger/5 border-danger/20" },
          { label: "Critical", count: critical.length, color: "text-warn bg-warn/5 border-warn/20" },
          { label: "Due This Week", count: dueSoon.length, color: "text-info bg-info/5 border-info/20" },
        ].map(s => (
          <div key={s.label} className={`rounded-xl border p-4 ${s.color}`}>
            <div className="text-xs font-medium opacity-70">{s.label}</div>
            <div className="text-2xl font-bold tabular mt-1">{s.count}</div>
          </div>
        ))}
      </div>

      {/* Digest preview */}
      <Card className="p-6">
        <div className="flex items-center gap-2 mb-4 border-b border-border pb-4">
          <FileText size={15} className="text-accent" />
          <span className="font-medium text-sm">Digest Preview</span>
          <span className="text-xs text-fg-muted ml-1">— copy this and paste into WhatsApp, email, or any chat</span>
        </div>
        <pre className="text-sm font-mono leading-relaxed whitespace-pre-wrap text-fg-muted bg-bg-subtle rounded-lg p-4 overflow-auto max-h-[60vh]">
          {digestText}
        </pre>
      </Card>

      {/* Section breakdowns */}
      {overdue.length > 0 && (
        <section>
          <h2 className="text-xs font-medium uppercase tracking-wider text-danger mb-3">🔴 Overdue</h2>
          <div className="space-y-2">
            {overdue.map(r => (
              <div key={r.id} className="card p-3 flex items-start gap-3 border-l-2 border-danger">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-xs text-fg-muted">{r.code}</span>
                    <span className="text-xs text-fg-muted">{r.companyName}</span>
                    {typeof r.daysToDeadline === "number" && r.daysToDeadline < 0 && (
                      <span className="text-xs font-medium text-danger">{Math.abs(r.daysToDeadline)}d late</span>
                    )}
                  </div>
                  <p className="text-sm mt-0.5">{r.actionItem}</p>
                  {r.latestUpdate && <p className="text-xs text-fg-muted mt-1 italic">{r.latestUpdate}</p>}
                </div>
                <span className="text-xs text-fg-muted shrink-0">{r.assignees.join(", ") || r.owner || ""}</span>
              </div>
            ))}
          </div>
        </section>
      )}

      {dueSoon.length > 0 && (
        <section>
          <h2 className="text-xs font-medium uppercase tracking-wider text-warn mb-3">📅 Due This Week</h2>
          <div className="space-y-2">
            {dueSoon.map(r => (
              <div key={r.id} className="card p-3 flex items-start gap-3 border-l-2 border-warn">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-xs text-fg-muted">{r.code}</span>
                    <span className="text-xs text-fg-muted">{r.companyName}</span>
                    <span className="text-xs text-warn font-medium">Due {fmtDate(r.deadline)}</span>
                  </div>
                  <p className="text-sm mt-0.5">{r.actionItem}</p>
                </div>
                <span className="text-xs text-fg-muted shrink-0">{r.assignees.join(", ") || r.owner || ""}</span>
              </div>
            ))}
          </div>
        </section>
      )}

      {recentlyClosed.length > 0 && (
        <section>
          <h2 className="text-xs font-medium uppercase tracking-wider text-success mb-3">✅ Recently Completed</h2>
          <div className="space-y-2">
            {recentlyClosed.slice(0, 10).map(r => (
              <div key={r.id} className="card p-3 flex items-start gap-3 border-l-2 border-success opacity-75">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs text-fg-muted">{r.code}</span>
                    <span className="text-xs text-fg-muted">{r.companyName}</span>
                  </div>
                  <p className="text-sm mt-0.5 line-through text-fg-muted">{r.actionItem}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
